name: 'hax'
description: 'Install hax and setup F*'
inputs:
  hax_reference:
    required: true
    default: "main"
  hax_repository:
    required: true
    default: "github:hacspec/hax"
  fstar:
    required: true
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Install & configure Cachix
      shell: bash
      run: |
        nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
        cachix use hax
    
    - name: Install F*
      shell: bash
      run: |
        VARIANT="Linux-x86_64"
        curl -sL "https://github.com/FStarLang/FStar/releases/download/$FSTAR/fstar-$FSTAR-$VARIANT.tar.gz" -o fstar.tar.gz
        tar -xzf fstar.tar.gz
        mv fstar hax-actions-fstar-binary
        echo "$PWD/hax-actions-fstar-binary/bin" >> $GITHUB_PATH
      env:
        FSTAR: "${{ inputs.fstar }}"
        OS: "${{ runner.os }}"

    - name: Install hax
      shell: bash
      run: nix profile install "$FLAKE"#hax
      env:
        FLAKE: "${{ inputs.hax_repository }}/${{ inputs.hax_reference }}"

