name: 'hax'
description: 'Install hax and setup F*'
inputs:
  hax_reference:
    required: true
    default: "main"
  hax_repository:
    required: true
    default: "github:hacspec/hax"
  fstar:
    required: true
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v4
      with:
        determinate: true
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install F*
      shell: bash
      run: nix profile install "$FLAKE"
      env:
        FLAKE: "github:fstarlang/fstar/${{ inputs.fstar }}"
    - name: Install hax
      shell: bash
      run: nix profile install "$FLAKE"#hax
      env:
        FLAKE: "${{ inputs.hax_repository }}/${{ inputs.hax_reference }}"
