name: 'hax'
description: 'Install hax and setup F*'
inputs:
  hax_reference:
    required: true
    default: "main"
  hax_repository:
    required: true
    default: "github:hacspec/hax"
  fstar:
    required: true
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Install & configure Cachix
      shell: bash
      run: |
        nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
        cachix use hax

    - name: Install hax
      shell: bash
      run: nix profile install "$FLAKE"#hax
      env:
        FLAKE: "${{ inputs.hax_repository }}/${{ inputs.hax_reference }}"

    - name: Install F*
      shell: bash
      run: |
        VARIANT="Linux-x86_64"
        mkdir -p hax-actions-fstar-binary
        cd hax-actions-fstar-binary
        curl -sL "https://github.com/FStarLang/FStar/releases/download/$FSTAR/fstar-$FSTAR-$VARIANT.tar.gz" | tar xvz -
        echo "$PWD/bin" >> $GITHUB_PATH
      env:
        FSTAR: "${{ inputs.fstar }}"
        OS: "${{ runner.os }}"
