name: test action

on:
  push:

jobs:
  test-action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: hacspec/hax-actions@main
      - run: |
          echo "HAX_PROOF_LIBS=$HAX_PROOF_LIBS"
          echo "HAX_LIB=$HAX_LIB"
          echo "HACL_HOME=$HACL_HOME"
          echo "F* version"
          fstar.exe --version
          echo "hax help"
          cargo hax --help
